"use client";

import { usePrivy, useWallets } from "@privy-io/react-auth";
import { useCallback, useEffect, useRef, useState } from "react";
import { useKynloAccountConfiguration } from "./kynlo-account-provider";
import "./base-sepolia-beta.css";
import "./base-sepolia-beta-status.css";

const CHAIN_ID="0x14a34";
const CHAIN={chainId:CHAIN_ID,chainName:"Base Sepolia",nativeCurrency:{name:"Ether",symbol:"ETH",decimals:18},rpcUrls:["https://sepolia.base.org"],blockExplorerUrls:["https://sepolia.basescan.org"]};
export const KYNLO_BASE_SEPOLIA={registry:"0x7A7a24163aF14050D21eDe38082b9fb101aB19FD",vault:"0xE2748286Ea7Aac6340084df8D847580D9b98F57E",mockAsset:"0xE37E2D655600690bd416B821A6dedc407D13FD29"} as const;
type Provider={request(args:{method:string;params?:unknown[]}):Promise<unknown>;on?:(e:string,l:(...a:unknown[])=>void)=>void;removeListener?:(e:string,l:(...a:unknown[])=>void)=>void};
type Draft={id:number;wallet:string;email:string};
type Snapshot={owner:string;state:number;armed:boolean;hasAssets:boolean;lastCheckIn:bigint};
const addr=/^0x[0-9a-fA-F]{40}$/; const email=/^[^\s@]+@[^\s@]+\.[^\s@]+$/;
const sleep=(ms:number)=>new Promise(r=>setTimeout(r,ms));
const short=(a:string)=>a?`${a.slice(0,6)}…${a.slice(-4)}`:"NOT CONNECTED";
const utf8=(v:string)=>`0x${Array.from(new TextEncoder().encode(v),b=>b.toString(16).padStart(2,"0")).join("")}`;
const word=(v:bigint|number|string)=>(typeof v==="bigint"?v:BigInt(v)).toString(16).padStart(64,"0");
const aw=(a:string)=>a.toLowerCase().replace(/^0x/,"").padStart(64,"0");
const allocations=(n:number)=>n===1?[10000]:n===2?[5000,5000]:[3334,3333,3333];
const stateNames=["DRAFT","ACTIVE","PROTECTION","SUCCESSION READY","CANCELLED","COMPLETED"];
async function sel(p:Provider,s:string){const h=await p.request({method:"web3_sha3",params:[utf8(s)]});if(typeof h!=="string"||h.length<10)throw new Error("Wallet RPC could not derive a function selector.");return h.slice(2,10)}
async function call(p:Provider,data:string){const r=await p.request({method:"eth_call",params:[{to:KYNLO_BASE_SEPOLIA.vault,data},"latest"]});if(typeof r!=="string")throw new Error("Could not read the Legacy Plan from Base Sepolia.");return r}
const chunk=(hex:string,i:number)=>hex.replace(/^0x/,"").slice(i*64,(i+1)*64);
async function receipt(p:Provider,h:string){for(let i=0;i<90;i++){const r=await p.request({method:"eth_getTransactionReceipt",params:[h]});if(r&&typeof r==="object"){if((r as {status?:string}).status==="0x0")throw new Error("Transaction reverted on Base Sepolia.");return}await sleep(1000)}throw new Error("Transaction confirmation timed out.")}
async function send(p:Provider,from:string,to:string,data:string){const h=await p.request({method:"eth_sendTransaction",params:[{from,to,data}]});if(typeof h!=="string")throw new Error("Wallet did not return a transaction hash.");await receipt(p,h);return h}
function err(e:unknown){return e instanceof Error?e.message.replace(/^Error:\s*/i,""):"Transaction was cancelled or failed."}

function Configured(){
 const {authenticated,user,login,linkEmail,linkWallet}=usePrivy(); const {wallets}=useWallets();
 const wallet=wallets.find(w=>w.walletClientType==="privy")??wallets[0]; const account=wallet?.address??"";
 const [provider,setProvider]=useState<Provider>(); const [chain,setChain]=useState(""); const [contracts,setContracts]=useState<boolean|null>(null);
 const [message,setMessage]=useState("Sign in with email or wallet to compose a live Base Sepolia Legacy Plan."); const [busy,setBusy]=useState("");
 const [successors,setSuccessors]=useState<Draft[]>([{id:1,wallet:"",email:""},{id:2,wallet:"",email:""}]); const [raw,setRaw]=useState("1000"); const [planId,setPlanId]=useState(""); const [tx,setTx]=useState(""); const [snap,setSnap]=useState<Snapshot|null>(null); const [reading,setReading]=useState(false); const [holding,setHolding]=useState(false); const holdTimer=useRef<ReturnType<typeof setTimeout>|null>(null);
 const onBase=chain.toLowerCase()===CHAIN_ID; const ready=Boolean(authenticated&&user?.email?.address&&account&&provider&&onBase&&contracts); const shares=allocations(successors.length);
 const sync=useCallback(async()=>{if(!provider)return;const c=await provider.request({method:"eth_chainId"});setChain(typeof c==="string"?c:"")},[provider]);
 const readPlan=useCallback(async(idText=planId)=>{if(!provider||!onBase||!idText){setSnap(null);return}setReading(true);try{const id=BigInt(idText);const getter=await sel(provider,"legacyPlans(uint256)");const rawPlan=await call(provider,`0x${getter}${word(id)}`);const owner=`0x${chunk(rawPlan,0).slice(24)}`;if(/^0x0{40}$/i.test(owner)){setSnap(null);return}const stateFn=await sel(provider,"getEffectiveState(uint256)");const rawState=await call(provider,`0x${stateFn}${word(id)}`);const assetsFn=await sel(provider,"getAssets(uint256)");const rawAssets=await call(provider,`0x${assetsFn}${word(id)}`);const state=Number(BigInt(`0x${chunk(rawState,0)}`));const hasAssets=BigInt(`0x${chunk(rawAssets,1)||"0"}`)>0n;setSnap({owner,state,armed:BigInt(`0x${chunk(rawPlan,6)}`)!==0n,hasAssets,lastCheckIn:BigInt(`0x${chunk(rawPlan,2)}`)});}catch{setSnap(null)}finally{setReading(false)}},[provider,onBase,planId]);
 useEffect(()=>{const s=localStorage.getItem("kynlo-beta-plan-id");if(s)setPlanId(s)},[]);
 useEffect(()=>{let live=true;if(!wallet){setProvider(undefined);return}void wallet.getEthereumProvider().then(p=>{if(live)setProvider(p as Provider)});return()=>{live=false}},[wallet]);
 useEffect(()=>{void sync();if(!provider?.on)return;const f=()=>void sync();provider.on("chainChanged",f);return()=>provider.removeListener?.("chainChanged",f)},[provider,sync]);
 useEffect(()=>{if(!provider||!onBase){setContracts(null);return}Promise.all([KYNLO_BASE_SEPOLIA.registry,KYNLO_BASE_SEPOLIA.vault,KYNLO_BASE_SEPOLIA.mockAsset].map(a=>provider.request({method:"eth_getCode",params:[a,"latest"]}))).then(v=>setContracts(v.every(x=>typeof x==="string"&&x!=="0x"))).catch(()=>setContracts(false))},[provider,onBase]);
 useEffect(()=>{void readPlan()},[readPlan]);
 const connect=()=>{if(!authenticated)return login({loginMethods:["email","wallet"]});if(!user?.email?.address)return linkEmail();if(!wallet)return linkWallet({walletChainType:"ethereum-only"});setMessage("Kynlo account ready.")};
 const switchNet=async()=>{if(!provider)return;try{await provider.request({method:"wallet_switchEthereumChain",params:[{chainId:CHAIN_ID}]})}catch{await provider.request({method:"wallet_addEthereumChain",params:[CHAIN]})}await sync()};
 const run=async(label:string,fn:()=>Promise<string|void>)=>{if(!ready||busy)return;setBusy(label);setTx("");try{const h=await fn();if(h)setTx(h);await readPlan()}catch(e){setMessage(err(e))}finally{setBusy("")}};
 const create=()=>run("create",async()=>{if(!provider)return;if(successors.some(s=>!addr.test(s.wallet)))throw new Error("Every Successor needs a valid receiving wallet.");if(successors.some(s=>s.email&&!email.test(s.email)))throw new Error("Check each contact email.");const ws=successors.map(s=>s.wallet.toLowerCase());if(new Set(ws).size!==ws.length||ws.includes(account.toLowerCase()))throw new Error("Successor wallets must be unique and different from the owner.");const ns=await sel(provider,"nextPlanId()");const nr=await call(provider,`0x${ns}`);const id=BigInt(nr).toString();const fn=await sel(provider,"createLegacyPlan((address,uint16)[],uint64,uint64)");const head=`${word(96)}${word(90*86400)}${word(30*86400)}`;const tail=`${word(successors.length)}${successors.map((s,i)=>`${aw(s.wallet)}${word(shares[i])}`).join("")}`;setMessage("Confirm Legacy Plan creation.");const h=await send(provider,account,KYNLO_BASE_SEPOLIA.vault,`0x${fn}${head}${tail}`);setPlanId(id);localStorage.setItem("kynlo-beta-plan-id",id);setMessage(`Legacy Plan #${id} created. Fund the Vault next.`);setTimeout(()=>void readPlan(id),250);return h});
 const deposit=()=>run("deposit",async()=>{if(!provider)return;const id=BigInt(planId||"0"),amount=BigInt(raw||"0");if(id<=0n||amount<=0n)throw new Error("Enter a valid Plan ID and amount.");if(snap&&snap.owner.toLowerCase()!==account.toLowerCase())throw new Error("Connect the owner wallet for this Legacy Plan.");if(snap&&snap.state!==0&&snap.state!==1)throw new Error(`Deposits are unavailable while the plan is ${stateNames[snap.state]}.`);const ap=await sel(provider,"approve(address,uint256)");setMessage("1/2 Confirm MOCK-B20 approval.");await send(provider,account,KYNLO_BASE_SEPOLIA.mockAsset,`0x${ap}${aw(KYNLO_BASE_SEPOLIA.vault)}${word(amount)}`);const dp=await sel(provider,"depositAsset(uint256,address,uint256)");setMessage("2/2 Confirm Kynlo Vault deposit.");const h=await send(provider,account,KYNLO_BASE_SEPOLIA.vault,`0x${dp}${word(id)}${aw(KYNLO_BASE_SEPOLIA.mockAsset)}${word(amount)}`);setMessage(`Vault funded for Legacy Plan #${id}. Hold to Seal.`);return h});
 const seal=()=>run("seal",async()=>{if(!provider)return;const id=BigInt(planId||"0");if(!snap)throw new Error("Load a valid Legacy Plan first.");if(snap.owner.toLowerCase()!==account.toLowerCase())throw new Error("Only the owner wallet can Seal this plan.");if(snap.state!==0)throw new Error(`This plan is already ${stateNames[snap.state]}.`);if(!snap.hasAssets)throw new Error("Fund the Kynlo Vault before Sealing.");const fn=await sel(provider,"armLegacyPlan(uint256)");setMessage("Confirm Seal in the owner wallet.");const h=await send(provider,account,KYNLO_BASE_SEPOLIA.vault,`0x${fn}${word(id)}`);setMessage(`Legacy Plan #${id} is SEALED and ACTIVE.`);return h});
 const checkin=()=>run("checkin",async()=>{if(!provider)return;const id=BigInt(planId||"0");if(!snap)throw new Error("Load a valid Legacy Plan first.");if(snap.owner.toLowerCase()!==account.toLowerCase())throw new Error("Only the owner wallet can record Proof of Life.");if(snap.state!==1&&snap.state!==2)throw new Error(`Proof of Life is unavailable while the plan is ${stateNames[snap.state]}. Seal the plan first.`);const fn=await sel(provider,"checkIn(uint256)");setMessage("Confirm Proof of Life.");const h=await send(provider,account,KYNLO_BASE_SEPOLIA.vault,`0x${fn}${word(id)}`);setMessage(`Proof of Life recorded for Legacy Plan #${id}.`);return h});
 const startHold=()=>{if(!ready||busy||!snap||snap.state!==0||!snap.hasAssets)return;setHolding(true);holdTimer.current=setTimeout(()=>{setHolding(false);void seal()},900)}; const cancelHold=()=>{if(holdTimer.current)clearTimeout(holdTimer.current);holdTimer.current=null;setHolding(false)};
 const valid=successors.every(s=>addr.test(s.wallet)&&(!s.email||email.test(s.email))); const state=snap?stateNames[snap.state]:"NO PLAN LOADED";
 return <section className="beta-console" id="beta" aria-label="Kynlo Base Sepolia beta">
  <div className="composer-intro"><p className="eyebrow">LEGACY PLAN COMPOSER · BASE SEPOLIA</p><div><h2>Set your Legacy Plan.</h2><p>Name up to three Successors, fund the Vault, Seal the plan, then keep it active with Proof of Life.</p></div></div>
  <div className="mobile-flow-nav"><span>01 COMPOSE</span><span>02 FUND</span><span>03 SEAL</span><span>04 ACTIVE</span></div>
  <div className="composer-shell"><aside className="composer-rail"><div className="rail-kicker">PLAN / {planId||"DRAFT"}</div><ol><li className={!snap?"is-current":""}><span>01</span><b>Compose</b><small>Owner + Successors</small></li><li className={snap?.state===0&&!snap.hasAssets?"is-current":""}><span>02</span><b>Fund</b><small>Deposit asset</small></li><li className={snap?.state===0&&snap.hasAssets?"is-current":""}><span>03</span><b>Seal</b><small>Activate plan</small></li><li className={snap?.state===1?"is-current":""}><span>04</span><b>Active</b><small>Proof of Life</small></li></ol><div className="rail-status"><i className={ready?"is-live":""}/><span>{ready?"READY ON BASE SEPOLIA":"ACTION REQUIRED"}</span></div></aside>
   <div className="composer-workspace"><div className="composer-toolbar"><div><small>OWNER</small><strong>{short(account)}</strong></div><div><small>NETWORK</small><strong>{onBase?"BASE SEPOLIA":"NOT READY"}</strong></div>{!authenticated?<button onClick={connect}>EMAIL OR WALLET SIGN IN</button>:!user?.email?.address?<button onClick={connect}>VERIFY EMAIL</button>:!account?<button onClick={connect}>LINK WALLET</button>:!onBase?<button onClick={switchNet}>SWITCH NETWORK</button>:<span className="connected-chip">CONNECTED</span>}</div>
    <div className="ownership-canvas"><div className="canvas-axis"><span>OWNERSHIP →</span><span>TIME ↓</span></div><div className="owner-node"><small>OWNER</small><strong>{short(account)}</strong><span>100%</span></div><div className="ownership-trunk"/><div className={`successor-grid successor-count-${successors.length}`}>{successors.map((s,i)=><div className={addr.test(s.wallet)?"successor-node is-valid":"successor-node"} key={s.id}><div className="successor-heading"><small>SUCCESSOR {String.fromCharCode(65+i)}</small><b>{(shares[i]/100).toFixed(shares[i]%100?2:0)}%</b></div><label><span>WALLET ADDRESS</span><input value={s.wallet} onChange={e=>setSuccessors(x=>x.map(v=>v.id===s.id?{...v,wallet:e.target.value.trim()}:v))} placeholder="0x wallet address"/></label><label><span>CONTACT EMAIL · OPTIONAL</span><input type="email" value={s.email} onChange={e=>setSuccessors(x=>x.map(v=>v.id===s.id?{...v,email:e.target.value.trim()}:v))} placeholder="Notify this Successor"/></label><span className="successor-validity">{addr.test(s.wallet)?"RECEIVING WALLET VALID":"AWAITING WALLET"}</span>{successors.length>1?<button className="remove-successor" onClick={()=>setSuccessors(x=>x.filter(v=>v.id!==s.id))}>REMOVE</button>:null}</div>)}</div><div className="successor-controls"><button onClick={()=>setSuccessors(x=>x.length<3?[...x,{id:Math.max(...x.map(v=>v.id))+1,wallet:"",email:""}]:x)} disabled={successors.length>=3}>+ ADD SUCCESSOR</button><span>{successors.length} / 3 SUCCESSORS</span></div></div>
    <div className="plan-document"><div className="document-head"><span>KYNLO / LEGACY PLAN</span><b>{planId?`#${planId}`:"DRAFT"}</b></div><div className="document-grid"><div><small>INACTIVITY PERIOD</small><strong>90 DAYS</strong><p>Proof of Life keeps the plan active.</p></div><div><small>PROTECTION WINDOW</small><strong>30 DAYS</strong><p>Nothing moves while recovery remains open.</p></div><div><small>SUCCESSORS</small><strong>{successors.length} PATH{successors.length===1?"":"S"}</strong><p>Receiving wallets define the succession path.</p></div></div><button className="create-plan-action" disabled={!ready||!valid||!!busy} onClick={create}>{busy==="create"?"CREATING PLAN…":"CREATE LEGACY PLAN"}<span>↗</span></button></div>
   </div></div>
  {planId?<div className={`live-plan-panel ${snap&&snap.state>1?"is-warning":""}`}><div className="live-plan-main"><span className="live-plan-kicker"><i/>{reading?"READING BASE SEPOLIA":`ONCHAIN STATE · PLAN #${planId}`}</span><h3>{reading?"Checking…":state}</h3><p>{snap?.state===0?(snap.hasAssets?"Vault funded. Hold Seal to activate this Legacy Plan.":"Draft exists onchain. Fund the Vault to continue."):snap?.state===1?"Legacy Plan is active. Proof of Life is available now.":snap?.state===2?"Protection Window is active. Proof of Life can restore the plan.":snap?"This status is read directly from the Kynlo Vault on Base Sepolia.":"Enter a valid Plan ID owned by the connected wallet."}</p></div><div className="live-plan-meta"><div><small>OWNER</small><strong>{snap?short(snap.owner):"—"}</strong></div><div><small>VAULT</small><strong>{snap?.hasAssets?"FUNDED":"NOT FUNDED"}</strong></div><div><small>SEALED</small><strong>{snap?.armed?"YES":"NO"}</strong></div><div><small>NETWORK</small><strong>BASE SEPOLIA</strong></div></div></div>:null}
  <div className="execution-strip"><article><span>02 / FUND</span><h3>Place an asset inside the Vault.</h3><label>PLAN ID<input inputMode="numeric" value={planId} onChange={e=>{const v=e.target.value.replace(/\D/g,"");setPlanId(v);localStorage.setItem("kynlo-beta-plan-id",v)}}/></label><label>MOCK-B20 RAW AMOUNT<input inputMode="numeric" value={raw} onChange={e=>setRaw(e.target.value.replace(/\D/g,""))}/></label><button disabled={!ready||!planId||!!busy||Boolean(snap&&snap.state!==0&&snap.state!==1)} onClick={deposit}>{busy==="deposit"?"DEPOSITING…":"APPROVE + DEPOSIT"}</button></article>
   <article><span>03 / SEAL + ACTIVE</span><h3>{snap?.state===1?"Your Legacy Plan is active.":"Turn the draft into an active plan."}</h3><p>{snap?.state===1?"Use Proof of Life whenever you want to refresh the inactivity clock.":"Fund the Vault first, then press and hold for a moment to Seal."}</p><button className={`hold-seal ${holding?"is-holding":""}`} disabled={!ready||!!busy||!snap||snap.state!==0||!snap.hasAssets} onPointerDown={startHold} onPointerUp={cancelHold} onPointerLeave={cancelHold} onPointerCancel={cancelHold}>{busy==="seal"?"SEALING…":holding?"KEEP HOLDING…":snap?.state===1?"SEALED · ACTIVE":"HOLD TO SEAL"}</button><span className="hold-hint">HOLD FOR 0.9 SECONDS</span><button className="quiet-action" disabled={!ready||!!busy||!snap||(snap.state!==1&&snap.state!==2)} onClick={checkin}>{busy==="checkin"?"CHECKING IN…":"PROOF OF LIFE"}</button></article></div>
  <div className="beta-feedback"><div><small>LIVE STATUS</small><p>{busy?`Waiting for ${busy} transaction…`:message}</p></div>{tx?<a href={`https://sepolia.basescan.org/tx/${tx}`} target="_blank" rel="noreferrer">VIEW TRANSACTION ↗</a>:null}</div>
 </section>
}
export function BaseSepoliaBeta(){const {configured}=useKynloAccountConfiguration();if(!configured)return <section className="beta-console" id="beta"><div className="composer-intro"><p className="eyebrow">LEGACY PLAN COMPOSER · BASE SEPOLIA</p><div><h2>Account access is being connected.</h2><p>Add the Kynlo Privy App ID to enable sign-in.</p></div></div></section>;return <Configured/>}
